### ISSUE TITLE
Wrong usage example is generated

### ISSUE THREAD

**Issue by joachimdalen** [joachimdalen/azext#29]
Generated example:

```yaml
- task: AzExt Changelog@0.0.1
  inputs:
    command: generate
    output: CHANGELOG.md
    configName: changelog-config.json

```
- Should only use `Major` version
- Should use `name` instead of `friendlyName` for title
